version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongoDB
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: 'PetShelter'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'pOLDUProPJ'
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  mongodb-data:
  postgres_data:
